# vim:ft=conf
#export LANG=zh_CN.UTF-8
#export LANGUAGE=zh_CN:en_US
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

setxkbmap -layout br,ru,cn -option grp:win_space_toggle &
picom &
nm-applet &
mpd &
unclutter &
pipewire &
dunst &
setbg &

exec i3
